{"uid":"22bb3d5ddc31dedf","name":"Checkout two items and check if the total sum of the price matches.","fullName":"cypress/e2e/checkout.cy.ts#Assert if the checkout feature is working as it should. Checkout two items and check if the total sum of the price matches.","historyId":"4d9d5c8f71c75e8224a75430e70d67fb:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1728348860332,"stop":1728348861586,"duration":1254},"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.getByDataTest()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command","statusTrace":"CypressError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.getByDataTest()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command\n    at cy.<computed> [as getByDataTest] (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:138205:64)\nFrom Your Spec Code:\n    at Context.eval (webpack://cypress-ecommerce-automation/./cypress/support/commands.ts:72:0)\nFrom Your Spec Code:\n    at Context.eval (webpack://cypress-ecommerce-automation/./cypress/support/commands.ts:72:0)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"\"before each\" hook","time":{"start":1728348860338,"stop":1728348861154,"duration":816},"status":"passed","steps":[{"name":"Command \"loginViaUi\"","time":{"start":1728348861606,"stop":1728348860368,"duration":-1238},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"standard_user"},{"name":"Argument [1]","value":"secret_sauce"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"visit\"","time":{"start":1728348861606,"stop":1728348860505,"duration":-1101},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"/"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"getByDataTest\"","time":{"start":1728348861606,"stop":1728348860505,"duration":-1101},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"username"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"get\"","time":{"start":1728348861606,"stop":1728348860509,"duration":-1097},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"[data-test=username]"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"type\"","time":{"start":1728348861606,"stop":1728348860788,"duration":-818},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"standard_user"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"getByDataTest\"","time":{"start":1728348861606,"stop":1728348860788,"duration":-818},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"password"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"get\"","time":{"start":1728348861606,"stop":1728348860791,"duration":-815},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"[data-test=password]"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"type\"","time":{"start":1728348861606,"stop":1728348861057,"duration":-549},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"secret_sauce"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"getByDataTest\"","time":{"start":1728348861606,"stop":1728348861057,"duration":-549},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"login-button"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"get\"","time":{"start":1728348861606,"stop":1728348861060,"duration":-546},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"[data-test=login-button]"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"click\"","time":{"start":1728348861606,"stop":1728348861150,"duration":-456},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Command \"getByClass\"","time":{"start":1728348861606,"stop":1728348861150,"duration":-456},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"app_logo"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"get\"","time":{"start":1728348861606,"stop":1728348861155,"duration":-451},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":".app_logo"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":13,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.getByDataTest()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command","statusTrace":"CypressError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.getByDataTest()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command\n    at cy.<computed> [as getByDataTest] (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:138205:64)\nFrom Your Spec Code:\n    at Context.eval (webpack://cypress-ecommerce-automation/./cypress/support/commands.ts:72:0)\nFrom Your Spec Code:\n    at Context.eval (webpack://cypress-ecommerce-automation/./cypress/support/commands.ts:72:0)","steps":[{"name":"Command \"addItemToCart\"","time":{"start":1728348861606,"stop":1728348861157,"duration":-449},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"add-to-cart-sauce-labs-bike-light"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"getByDataTest\"","time":{"start":1728348861606,"stop":1728348861157,"duration":-449},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"add-to-cart-sauce-labs-bike-light"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"get\"","time":{"start":1728348861606,"stop":1728348861159,"duration":-447},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"[data-test=add-to-cart-sauce-labs-bike-light]"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"click\"","time":{"start":1728348861606,"stop":1728348861236,"duration":-370},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Command \"addItemToCart\"","time":{"start":1728348861606,"stop":1728348861237,"duration":-369},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"add-to-cart-sauce-labs-backpack"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"getByDataTest\"","time":{"start":1728348861606,"stop":1728348861237,"duration":-369},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"add-to-cart-sauce-labs-backpack"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"get\"","time":{"start":1728348861606,"stop":1728348861240,"duration":-366},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"[data-test=add-to-cart-sauce-labs-backpack]"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Command \"click\"","time":{"start":1728348861606},"status":"unknown","steps":[],"attachments":[{"uid":"bd419f74f1bc77d9","name":"Screenshot","source":"bd419f74f1bc77d9.png","type":"image/png","size":233080}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":8,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"parentSuite","value":"Assert if the checkout feature is working as it should."},{"name":"host","value":"fv-az692-231"},{"name":"thread","value":"pid-2847-worker-main"},{"name":"package","value":"cypress.e2e.checkout.cy.ts"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"561237e9f48e1480","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.getByDataTest()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command","time":{"start":1728348860283,"stop":1728348861536,"duration":1253}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"88a647f0800d3056","reportUrl":"https://bbgx.github.io/cypress-ecommerce-automation/15//#testresult/88a647f0800d3056","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.getByDataTest()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command","time":{"start":1728348456280,"stop":1728348457623,"duration":1343}}]},"tags":[]},"source":"22bb3d5ddc31dedf.json","parameterValues":[]}